first_name_only = false
show_receipts = true
notifications = true
bell = true
colored_messages = true
default_keybindings = false

[user]
display_name = "Henrik Bakken"

[keybindings.anywhere]
F1 = "help"
ctrl-q = "quit"
backspace = "delete_character previous"
alt-backspace = "kill_word"
delete = "delete_character next"

[keybindings.normal]
F2 = "toggle_channel_modal"
ctrl-n = "select_message next entry"
ctrl-p = "select_message previous entry"
alt-n = "select_channel next"
alt-p = "select_channel previous"
ctrl-x = "toggle_multiline"
ctrl-f = "move_text next word"
alt-f = "move_text next character"
ctrl-b = "move_text previous word"
alt-b = "move_text previous character"
ctrl-u = "kill_backward_line"
ctrl-w = "kill_word"
ctrl-a = "beginning_of_line"
ctrl-e = "end_of_line"
tab = "react"
# defaults
down = "select_channel next"
up = "select_channel previous"
home = "beginning_of_line"
end = "end_of_line"
pagedown = "select_message next entry"
pageup = "select_message previous entry"
ctrl-left = "move_text previous character"
ctrl-right = "move_text next character"
left = "move_text previous character"
right = "move_text next character"
alt-left = "move_text previous word"
alt-right = "move_text next word"
alt-up = "select_message previous entry"
alt-down = "select_message next entry"

[keybindings.message_selected]
alt-y = "copy_message selected"
ctrl-e = "edit_message"
ctrl-t = "react :thumbsup:"
ctrl-r = "react ❤️"

[keybindings.multiline]
ctrl-n = "move_text next line"
ctrl-p = "move_text previous line"
# defaults
down = "move_text next line"
up = "move_text previous line"

[keybindings.help]
esc = "help"
ctrl-n = "scroll help down entry"
ctrl-p = "scroll help up entry"
# defaults
down = "scroll help down entry"
up = "scroll help up entry"
pagedown = "scroll help down entry"
pageup = "scroll help up entry"

[keybindings.channel_modal]
F2 = "toggle_channel_modal"
ctrl-n = "select_channel_modal next"
ctrl-p = "select_channel_modal previous"
ctrl-f = "move_text next word"
ctrl-b = "move_text previous word"
alt-f = "move_text next character"
alt-b = "move_text previous character"
ctrl-u = "kill_backward_line"
ctrl-w = "kill_word"
ctrl-a = "beginning_of_line"
ctrl-e = "end_of_line"
alt-backspace = "kill_word"
# defaults
ctrl-left = "move_text previous character"
ctrl-right = "move_text next character"
down = "select_channel_modal next"
up = "select_channel_modal previous"
left = "move_text previous character"
right = "move_text next character"
alt-left = "move_text previous word"
alt-right = "move_text next word"
home = "beginning_of_line"
end = "end_of_line"
