add_newline = true
right_format = """$cmd_duration"""

[line_break]
disabled = true

[time]
disabled = false

[cmd_duration]
min_time = 1000
format = 'underwent [$duration](bold yellow)'
show_milliseconds = true

[directory]
truncation_length = 5
truncation_symbol = '…/'
repo_root_style = "red"
repo_root_format = ' [$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '

[git_branch]
symbol = " "

[git_status]
disabled = true

[package]
disabled = true

[python]
disabled = true
