
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies: 10.2.0.0/16

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: nordpool
    region: "Oslo"
    currency: "NOK"
    VAT: True
    precision: 3
    low_price_cutoff: 0.95
    price_in_cents: false
    price_type: kWh

    # Template to specify additional cost to be added to the tariff.
    # The template price is in EUR, DKK, NOK or SEK (not in cents).
    # For example: "{{ current_price * 0.19 + 0.023 | float}}" 
    additional_costs: "{{0.0|float}}"

google_assistant:
  project_id: homeassistant-mothership-1123
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
