
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies: 10.2.0.0/16

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

google_assistant:
  project_id: homeassistant-mothership-1123
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true

sensor:
  - platform: nordpool
    region: "Oslo"
    currency: "NOK"
    low_price_cutoff: 0.95
