
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies: 10.2.0.0/16

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

google_assistant:
  project_id: homeassistant-mothership-1123
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true

sensor:
- platform: nordpool
  region: "NO1"
  currency: "NOK"
  low_price_cutoff: 0.95
# - platform: template
#   sensors:
#     # NORDPOOL PRICES
#     nordpool_today_hr_00_01:
#       friendly_name: "Today hour 0"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[0] }}"
#     nordpool_today_hr_01_02:
#       friendly_name: "Today hour 1"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[1] }}"
#     nordpool_today_hr_02_03:
#       friendly_name: "Today hour 2"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[2] }}"
#     nordpool_today_hr_03_04:
#       friendly_name: "Today hour 3"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[3] }}"
#     nordpool_today_hr_04_05:
#       friendly_name: "Today hour 4"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[4] }}"
#     nordpool_today_hr_05_06:
#       friendly_name: "Today hour 5"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[5] }}"
#     nordpool_today_hr_06_07:
#       friendly_name: "Today hour 6"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[6] }}"
#     nordpool_today_hr_07_08:
#       friendly_name: "Today hour 7"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[7] }}"
#     nordpool_today_hr_08_09:
#       friendly_name: "Today hour 8"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[8] }}"
#     nordpool_today_hr_09_10:
#       friendly_name: "Today hour 9"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[9] }}"
#     nordpool_today_hr_10_11:
#       friendly_name: "Today hour 10"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[10] }}"
#     nordpool_today_hr_11_12:
#       friendly_name: "Today hour 11"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[11] }}"
#     nordpool_today_hr_12_13:
#       friendly_name: "Today hour 12"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[12] }}"
#     nordpool_today_hr_13_14:
#       friendly_name: "Today hour 13"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[13] }}"
#     nordpool_today_hr_14_15:
#       friendly_name: "Today hour 14"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[14] }}"
#     nordpool_today_hr_15_16:
#       friendly_name: "Today hour 15"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[15] }}"
#     nordpool_today_hr_16_17:
#       friendly_name: "Today hour 16"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[16] }}"
#     nordpool_today_hr_17_18:
#       friendly_name: "Today hour 17"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[17] }}"
#     nordpool_today_hr_18_19:
#       friendly_name: "Today hour 18"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[18] }}"
#     nordpool_today_hr_19_20:
#       friendly_name: "Today hour 19"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[19] }}"
#     nordpool_today_hr_20_21:
#       friendly_name: "Today hour 20"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[20] }}"
#     nordpool_today_hr_21_22:
#       friendly_name: "Today hour 21"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[21] }}"
#     nordpool_today_hr_22_23:
#       friendly_name: "Today hour 22"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[22] }}"
#     nordpool_today_hr_23_24:
#       friendly_name: "Today hour 23"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.today[23] }}"
#     nordpool_tomorrow_hr_00_01:
#       friendly_name: "Tomorrow hour 0"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[0] }}"
#     nordpool_tomorrow_hr_01_02:
#       friendly_name: "Tomorrow hour 1"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[1] }}"
#     nordpool_tomorrow_hr_02_03:
#       friendly_name: "Tomorrow hour 2"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[2] }}"
#     nordpool_tomorrow_hr_03_04:
#       friendly_name: "Tomorrow hour 3"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[3] }}"
#     nordpool_tomorrow_hr_04_05:
#       friendly_name: "Tomorrow hour 4"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[4] }}"
#     nordpool_tomorrow_hr_05_06:
#       friendly_name: "Tomorrow hour 5"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[5] }}"
#     nordpool_tomorrow_hr_06_07:
#       friendly_name: "Tomorrow hour 6"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[6] }}"
#     nordpool_tomorrow_hr_07_08:
#       friendly_name: "Tomorrow hour 7"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[7] }}"
#     nordpool_tomorrow_hr_08_09:
#       friendly_name: "Tomorrow hour 8"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[8] }}"
#     nordpool_tomorrow_hr_09_10:
#       friendly_name: "Tomorrow hour 9"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[9] }}"
#     nordpool_tomorrow_hr_10_11:
#       friendly_name: "Tomorrow hour 10"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[10] }}"
#     nordpool_tomorrow_hr_11_12:
#       friendly_name: "Tomorrow hour 11"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[11] }}"
#     nordpool_tomorrow_hr_12_13:
#       friendly_name: "Tomorrow hour 12"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[12] }}"
#     nordpool_tomorrow_hr_13_14:
#       friendly_name: "Tomorrow hour 13"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[13] }}"
#     nordpool_tomorrow_hr_14_15:
#       friendly_name: "Tomorrow hour 14"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[14] }}"
#     nordpool_tomorrow_hr_15_16:
#       friendly_name: "Tomorrow hour 15"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[15] }}"
#     nordpool_tomorrow_hr_16_17:
#       friendly_name: "Tomorrow hour 16"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[16] }}"
#     nordpool_tomorrow_hr_17_18:
#       friendly_name: "Tomorrow hour 17"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[17] }}"
#     nordpool_tomorrow_hr_18_19:
#       friendly_name: "Tomorrow hour 18"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[18] }}"
#     nordpool_tomorrow_hr_19_20:
#       friendly_name: "Tomorrow hour 19"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[19] }}"
#     nordpool_tomorrow_hr_20_21:
#       friendly_name: "Tomorrow hour 20"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[20] }}"
#     nordpool_tomorrow_hr_21_22:
#       friendly_name: "Tomorrow hour 21"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[21] }}"
#     nordpool_tomorrow_hr_22_23:
#       friendly_name: "Tomorrow hour 22"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[22] }}"
#     nordpool_tomorrow_hr_23_24:
#       friendly_name: "Tomorrow hour 23"
#       icon_template: mdi:cash
#       unit_of_measurement: "øre"
#       value_template: "{{ states.sensor.nordpool_kwh_oslo_nok_3_10_025.attributes.tomorrow[23] }}"
